# Generated by Django 3.0.8 on 2020-07-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignmentApp', '0002_auto_20200715_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
    ]
